### ISSUE TITLE
Check into the Dependabot tickets

### ISSUE THREAD

**Issue by mirzu** [emulsify-ds/emulsify_twig#12]
┆Issue is synchronized with this [Jira Story](https://fourkitchens.atlassian.net/browse/GS-190) by [Unito](https://www.unito.io/learn-more)

**Comment by codechefmarc** [comment]
Looks like Dependabot paused itself as we were not merging any of the auto-created PR's. I removed the stale PRs, and since this repo is going into archive mode soon, I'm going to close this. We'll move all development over to Emulsify Tools module where we can re-enable Dependabot if needed.
