### ISSUE TITLE
Research Existing Component Libraries

### ISSUE THREAD

**Issue by mirzu** [emulsify-ds/emulsify_twig#9]
┆Issue is synchronized with this [Jira Story](https://fourkitchens.atlassian.net/browse/GS-177) by [Unito](https://www.unito.io/learn-more)

**Comment by mirzu** [comment]
I Looked into a number of component libraries to see if they provide either inspiration or a legitimate starting point for us to pull from. Here are the ones that are worth keeping an eye on so far. Feel free to add to this list. 

- [Grommet](https://v2.grommet.io/) - Very well structured, great separation of concerns and a very well thought out theming layer. Even includes tools for [creating themes](https://theme-designer.grommet.io/Dashboard) and [compositing components](https://designer.grommet.io/) in the browser. 
- [Rebass](https://rebassjs.org/) - A more simplistic but also a clean slate starting point approach.
- [Baseweb](https://baseweb.design/) - A very in-depth library, and strong support for theming, but it's quite a bit more opinionated than the above two.

**Comment by codechefmarc** [comment]
Looks like @amazingrando moved this to done, so I'll close the issue as well.
